-- Insertions dans la table Pays
INSERT INTO Pays VALUES ('USA', 'États-Unis');
INSERT INTO Pays VALUES ('GBR', 'Grand-Bretagne');
INSERT INTO Pays VALUES ('FRA', 'France');
INSERT INTO Pays VALUES ('ITA', 'Italie'); 
INSERT INTO Pays VALUES ('JPN', 'Japon');
INSERT INTO Pays VALUES ('CAN', 'Canada');
INSERT INTO Pays VALUES ('AUS', 'Australie');
INSERT INTO Pays VALUES ('UKR', 'Ukraine');
INSERT INTO Pays VALUES ('BEL', 'Belgique');
INSERT INTO Pays VALUES ('NED', 'Pays-Bas');
INSERT INTO Pays VALUES ('TJK', 'Tadjikistan');
INSERT INTO Pays VALUES ('SUI', 'Suisse');
INSERT INTO Pays VALUES ('KOR', 'Corée du Sud');
INSERT INTO Pays VALUES ('SWE', 'Suède');
INSERT INTO Pays VALUES ('HUN', 'Hongrie');

-- Insertions dans la table Sport
INSERT INTO Sport VALUES (2, 'Natation');
INSERT INTO Sport VALUES (3, 'Cyclisme');
INSERT INTO Sport VALUES (4, 'Judo');
INSERT INTO Sport VALUES (5, 'Escrime');
INSERT INTO Sport VALUES (6, 'Triathlon');

-- Insertions dans la table Discipline
INSERT INTO Discipline VALUES (6, '50m nage libre', 2);
INSERT INTO Discipline VALUES (7, '400m 4 nages', 2);
INSERT INTO Discipline VALUES (8, '200m 4 nages', 2);
INSERT INTO Discipline VALUES (9, '100m dos', 2);
INSERT INTO Discipline VALUES (10, '200m papillon', 2);
INSERT INTO Discipline VALUES (12, 'Contre la montre - homme', 3);
INSERT INTO Discipline VALUES (13, 'Course en ligne', 3);
INSERT INTO Discipline VALUES (14, 'Cross-country', 3);
INSERT INTO Discipline VALUES (15, 'Contre la montre - femme', 3);
INSERT INTO Discipline VALUES (20, 'Judo +100kg', 4);
INSERT INTO Discipline VALUES (22, 'Triathlon', 6);
INSERT INTO Discipline VALUES (21, 'Fleuret individuel', 5);
INSERT INTO Discipline VALUES (23, 'Sabre individuel', 5);

-- Insertions dans la table Athlete
INSERT INTO Athlete VALUES (1, 'Leon', 'Marchand', '2002-05-17', 'FRA');
INSERT INTO Athlete VALUES (2, 'Kim', 'Minjong', '2000-09-01', 'KOR');
INSERT INTO Athlete VALUES (3, 'Remco', 'Evenepoel', '2000-01-25', 'BEL');
INSERT INTO Athlete VALUES (4, 'Teddy', 'Riner', '1989-04-07', 'FRA');
INSERT INTO Athlete VALUES (5, 'Cameron', 'McEvoy', '1994-05-13', 'AUS');
INSERT INTO Athlete VALUES (6, 'Manon', 'Apithy-Brunet', '1996-02-07', 'FRA');
INSERT INTO Athlete VALUES (7, 'Sara', 'Balzer', '1995-04-03', 'FRA');
INSERT INTO Athlete VALUES (8, 'Lee', 'Kiefer', '1994-06-15', 'USA');
INSERT INTO Athlete VALUES (9, 'Lauren', 'Scruggs', '2003-01-27', 'USA');
INSERT INTO Athlete VALUES (10, 'Eleanor', 'Harvey', '1995-01-14', 'CAN');
INSERT INTO Athlete VALUES (11, 'Olha', 'Kharlan', '1990-09-04', 'UKR');
INSERT INTO Athlete VALUES (12, 'Benjamin', 'Proud', '1994-09-21', 'GBR');
INSERT INTO Athlete VALUES (13, 'Florent', 'Manaudou', '1990-11-12', 'FRA');
INSERT INTO Athlete VALUES (14, 'Tomoyuki', 'Matsushita', '2005-08-01', 'JPN');
INSERT INTO Athlete VALUES (15, 'Carson', 'Foster', '2001-10-26', 'USA');
INSERT INTO Athlete VALUES (16, 'Filippo', 'Ganna', '1996-07-25', 'ITA');
INSERT INTO Athlete VALUES (17, 'Wout', 'vanAert', '1994-09-15', 'BEL');
INSERT INTO Athlete VALUES (18, 'Kristen', 'Faulkner', '1992-12-18', 'USA'); 
INSERT INTO Athlete VALUES (19, 'Marianne', 'Vos', '1987-05-13', 'NED');
INSERT INTO Athlete VALUES (20, 'Lotte', 'Kopecky', '1995-11-10', 'BEL'); 
INSERT INTO Athlete VALUES (21, 'Cassandre', 'Beaugrand', '1997-05-23', 'FRA'); 
INSERT INTO Athlete VALUES (22, 'Julie', 'Derron', '1996-09-10', 'SUI'); 
INSERT INTO Athlete VALUES (23, 'Beth', 'Potter', '1991-12-27', 'GBR'); 
INSERT INTO Athlete VALUES (24, 'Temur', 'Rakhimov', '1997-07-08', 'TJK');
INSERT INTO Athlete VALUES (26, 'Pauline', 'FerrandPrévot', '1992-02-10', 'FRA'); 
INSERT INTO Athlete VALUES (27, 'Haley', 'Batten', '1998-09-19', 'USA'); 
INSERT INTO Athlete VALUES (28, 'Jenny', 'Rissveds', '1994-06-06', 'SWE'); 
INSERT INTO Athlete VALUES (29, 'Emma', 'Lombardi', '2001-09-12', 'FRA'); 
INSERT INTO Athlete VALUES (30, 'Puck', 'Pieterse', '2002-05-13', 'NED'); 
INSERT INTO Athlete VALUES (31, 'Valentin', 'Madouas', '1996-07-12', 'FRA');
INSERT INTO Athlete VALUES (32, 'Christophe', 'Laporte', '1992-12-11', 'FRA');
INSERT INTO Athlete VALUES (33, 'Grace', 'Brown', '1992-07-07', 'AUS');
INSERT INTO Athlete VALUES (34, 'Anna', 'Henderson', '1998-11-14', 'GBR');
INSERT INTO Athlete VALUES (35, 'Chloe', 'Dygert', '1997-01-01', 'USA');
INSERT INTO Athlete VALUES (36, 'Labous', 'Juliette', '1998-11-04', 'FRA');
INSERT INTO Athlete VALUES (37, 'Demi', 'Vollering', '1996-11-15', 'NED');
INSERT INTO Athlete VALUES (38, 'Summer', 'McKintosh', '2006-08-18', 'AUS');
INSERT INTO Athlete VALUES (39, 'Kate', 'Douglas', '2001-11-17', 'AUS');
INSERT INTO Athlete VALUES (40, 'Kaylee', 'McKeown', '2001-07-12', 'AUS');
INSERT INTO Athlete VALUES (41, 'Regan', 'Smith', '2002-02-09', 'USA');
INSERT INTO Athlete VALUES (42, 'Katharine', 'Berkoff', '2001-01-28', 'USA');
INSERT INTO Athlete VALUES (43, 'Kristof', 'Milak', '2000-02-20', 'HUN');
INSERT INTO Athlete VALUES (44, 'Ilya', 'Kharun', '2005-02-07', 'CAN');

-- Insertions dans la table Participe
INSERT INTO Participe VALUES (1, 7, 1);
INSERT INTO Participe VALUES (2, 20, 2);
INSERT INTO Participe VALUES (3, 12, 1);
INSERT INTO Participe VALUES (4, 20, 1);
INSERT INTO Participe VALUES (5, 6, 1);
INSERT INTO Participe VALUES (6, 23, 1);
INSERT INTO Participe VALUES (7, 23, 2);
INSERT INTO Participe VALUES (8, 21, 1);
INSERT INTO Participe VALUES (9, 21, 2);
INSERT INTO Participe VALUES (10, 21, 3);
INSERT INTO Participe VALUES (11, 23, 3);
INSERT INTO Participe VALUES (12, 6, 2);
INSERT INTO Participe VALUES (13, 6, 3);
INSERT INTO Participe VALUES (14, 7, 2);
INSERT INTO Participe VALUES (15, 7, 3);
INSERT INTO Participe VALUES (16, 12, 2);
INSERT INTO Participe VALUES (17, 12, 3);
INSERT INTO Participe VALUES (18, 13, 1);
INSERT INTO Participe VALUES (19, 13, 2);
INSERT INTO Participe VALUES (20, 13, 3);
INSERT INTO Participe VALUES (21, 22, 1);
INSERT INTO Participe VALUES (22, 22, 2);
INSERT INTO Participe VALUES (23, 22, 3);
INSERT INTO Participe VALUES (24, 20, 3);
INSERT INTO Participe VALUES (26, 14, 1);
INSERT INTO Participe VALUES (27, 14, 2);
INSERT INTO Participe VALUES (28, 14, 3);
INSERT INTO Participe VALUES (29, 22, 4);
INSERT INTO Participe VALUES (30, 14, 4);
INSERT INTO Participe VALUES (3, 13, 1);
INSERT INTO Participe VALUES (31, 13, 2);
INSERT INTO Participe VALUES (32, 13, 3);
INSERT INTO Participe VALUES (33, 15, 1);
INSERT INTO Participe VALUES (34, 15, 2);
INSERT INTO Participe VALUES (35, 15, 3);
INSERT INTO Participe VALUES (36, 15, 4);
INSERT INTO Participe VALUES (37, 15, 5);
INSERT INTO Participe VALUES (20, 15, 6);
INSERT INTO Participe VALUES (38, 8, 1);
INSERT INTO Participe VALUES (39, 8, 2);
INSERT INTO Participe VALUES (40, 8, 3);
INSERT INTO Participe VALUES (40, 9, 1);
INSERT INTO Participe VALUES (41, 9, 2);
INSERT INTO Participe VALUES (42, 9, 3);
INSERT INTO Participe VALUES (1, 10, 1);
INSERT INTO Participe VALUES (43, 10, 2);
INSERT INTO Participe VALUES (44, 10, 3);
